# Generated by Django 5.1.3 on 2024-11-16 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerSuggestion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('flavor_suggestion', models.CharField(max_length=200)),
                ('allergy_concern', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='IngredientInventory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=80)),
                ('quantity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='SeasonalFlavor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=80)),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
